### ISSUE TITLE
database update process does not report numbers

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/pdb-annotation#15]
The output from running the update step of the pdb-alignment-pipeline should report the number of pdb files added, deleted, modified in the runtime report. Total Input Queries is reported in the runtime report below (596) --- this is good. We also would be able to report the number of deletions from the alignment table if we used a true database interaction rather than the external .sql script.

[SHELL] Weekly Update: Create deleted list
[Preprocessing] Preprocessing PDB sequences...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/sheridar/repos/sheridancbio/pdb-annotation/pdb-alignment-pipeline/target/pdb-alignment-pipeline-0.1.0.jar!/lib/logback-classic-1.1.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/sheridar/repos/sheridancbio/pdb-annotation/pdb-alignment-pipeline/target/pdb-alignment-pipeline-0.1.0.jar!/lib/log4j-slf4j-impl-2.4.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[BLAST] Running makeblastdb command...
[BLAST] Command makeblastdb complete
[BLAST] Running blastp command...
[BLAST] Command blastp complete
[BLAST] Read blast results from xml file...
[BLAST] Total Input Queries = 596
[SHELL] Start Write insert.sql File...
[SHELL] Write insert.sql Done
[DATABASE] Running mysql command...
[DATABASE] Command mysql complete
[Shell] Generating delete SQL
[DATABASE] Running mysql command...
[DATABASE] Command mysql complete
[Shell] All Execution time is 52.981 seconds

**Comment by juexinwang** [comment]
Done

**Comment by sheridancbio** [comment]
Insert statement count has been added. In the future we can elaborate if necessary.

2016-08-12 18:05:32 INFO  PdbScriptsPipelineMakeSQL:123 - [BLAST] Insert statements after parsing 0th xml : 26706

If we switch over to using a direct database interface interaction (instead of external process) we can get the number of records affected after an insert or delete.
