### ISSUE TITLE
Add "DATE_ADDED" field to table pdb_ensembl_alignment

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/pdb-annotation#16]
Since the alignment table is subject to modification, it would be helpful for development and debugging to know when records were added to the table. The same goes for pdb_entry and any other tables which are modified as part of the update process

**Comment by juexinwang** [comment]
I changed the pdb.sql and changed all the codes accordingly.

**Comment by juexinwang** [comment]
Done
