### ISSUE TITLE
construction of mysql command hardcodes max_allowed_packet setting

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/pdb-annotation#18]
in PdbScriptsPipelineRunCommand.java, we have:
        private List<String> makeDBCommand() {
                List<String> list = new ArrayList<String>();
                // Building the following process command
                list.add(rc.mysql);
                list.add("--max_allowed_packet=1024M");

This max_allowed_packet setting must be configured in both the client and in the mysqld server to function correctly. The setting should not be hardcoded here, but be set in application.properties

**Comment by juexinwang** [comment]
Thanks for your review, I will solve these one by one

**Comment by juexinwang** [comment]
Solved
