### ISSUE TITLE
rename db_schema in application.properties to db_name or db_database_name

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/pdb-annotation#19]
This property is to hold the name of the database which is being used to store data.

schema is a more general concept, as multiple databases can have identical schema.

In the mysql documentation, they use the pattern "db_name" to represent this string, for examples see: 
https://dev.mysql.com/doc/refman/5.7/en/mysql.html
https://dev.mysql.com/doc/refman/5.7/en/alter-database.html

**Comment by juexinwang** [comment]
I changed

**Comment by juexinwang** [comment]
Done
