### ISSUE TITLE
exception when "interval" properties divide evenly into alignment count

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/pdb-annotation#20]
The two application.properties settings:
ensembl_input_interval=10000
sql_insert_output_interval=10000

There are errors when these numbers evenly divide into the number of generated alignments. We need to add code into the pipeline to avoid these exceptions. We could try to detect and delete empty files before attempting to parse them .. or use clever record counting and interval number factorization (using disparate prime numbers)

**Comment by juexinwang** [comment]
Done
