### ISSUE TITLE
Choice : custom application.properties parser versus spring based properties

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/pdb-annotation#23]
There is currently custom code for parsing the properties files and making values available to the code. There are also spring based directives for connecting to properties files.

We should have one or the other.

If we keep the custom parsing code then:
- drop the spring annotations for properties processing
- make the parsing code function so that the file is parsed only once, values are cached in memory, and many java classes can read the properties without causing a new parsing of the file.

If we get the spring based property parsing to work, then remove the custom code, and replace all properties references using the spring framework.

**Comment by juexinwang** [comment]
I used  singleton design pattern to solved this problem.

**Comment by juexinwang** [comment]
Done
