### ISSUE TITLE
access levels not appropriate for data members

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/pdb-annotation#26]
PdbScriptsPipelineRunCommand.java has some public data members, and one which is not specified (so it defaults to "package" level access.

In general all data members should have access level "private" specified unless there is a good reason not to. Make these private or discuss alternatives.

**Comment by juexinwang** [comment]
I have sth to share, so I used several public here. I changed all unnecessary public.

**Comment by juexinwang** [comment]
Done

**Comment by sheridancbio** [comment]
The data members were changed to default [package] access level. The package access level is discouraged. These data member should all be made private:
    BlastDataBase db;
    int matches;
    int ensemblFileCount;
If access is needed outside of the class, add get() methods.

**Comment by juexinwang** [comment]
Done

**Comment by juexinwang** [comment]
I changed to private, add set and get functions

**Comment by sheridancbio** [comment]
Ok, closing issue ... but I did notice that Logger log is also not marked as access level private. If you get a chance, fix that one too.
