### ISSUE TITLE
PdbScriptsPipelineMakeSQL.java should be improved if we are keeping it

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/pdb-annotation#30]
If we are switching to using a direct DB interaction through a java repository, then this class will be mostly deleted.

Otherwise, responsibilities should be grouped and broken out into other classes. One example might be to separate the parsing of blast xml, and separate the generation of insert statements.

Other improvements:
- [x] "choose" argument into parse2sql should be renamed so that it is clear what choice is being made. Also "1" and "0" as choices are unclear. Maybe use an enum with named values ... or define static final int class members at least.
- [x] parseblastresults : we have alternatives SmallMem and Single, but maybe there is no use for Single? If SmallMem will always work, drop Single from code.

**Comment by juexinwang** [comment]
Yes, SmallMem and Single may be dropped. But it is efficient and quick for it did not divide the original size of the input

**Comment by juexinwang** [comment]
Done
