### ISSUE TITLE
Does the "updateweekly" mode work correctly currently?

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/pdb-annotation#34]
I have not tested the scheduled weekly updates using the Calendar function and Timer.schedule option.

From looking at the code it seems that it will run the update at a future time and then exit .. but won't the user need to reset this process after each update?  If the user needs to reset after each week, then they are not saving any time compared to running the process manually each week. So I think the internal scheduler should loop ... scheduling the next update after it finishes each update.

If the desired functionality is that the program run continuously in this mode, running each week without needing to be manually restarted by an external user, then convert this issue from "Question" to "Bug" (unless the code is functioning correctly already and I misunderstood it).

**Comment by juexinwang** [comment]
Yes, The user does not need to reset by "weekly update". The inner java schedule dealt with it well
