### ISSUE TITLE
Rev2: changes to the gsoc project completion wiki page

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/pdb-annotation#38]
Here are some suggested improvements and points of feedback:
- [x] The title of the page doesn't need to say "wiki", since that is obvious because the page is found under the "wiki" tab. It also doesn't need to say pdb-annotation .. since visitors already know the project they are looking at. For a title, describe what this particular wiki page is meant to capture .. my suggestion: "gsoc 2016 project summary and guide"
- [x] delete the welcome line (not helpful)
- [x] Use better text formatting and indentation to make clear which parts of the instructions in section 2 (Installation Guide) are "commands for the user to type". If these are all in a distinctive font and have a standard indent it makes it much easier for the reader to know what they are supposed to type and where they are in the process.
- [x] The instructions themselves in section 2 (Installation Guide) should be rewritten so that someone who knows _nothing_ about the project will still be able to know what to do and how to get the program installed and running. Too many of these instructions assume the user knows the project and can figure out appropriate settings ... and some of the example file paths will probably need to be different depending on where the user chooses to install and run the code.
- [x] the API Documentation Section "Functional Details" for the first API endpoint is not accurate. Rewrite this text so it describes what the API actually does
- [x] the one main figure / diagram is good. Look for other opportunities to present helpful images which capture the purpose of document sections "at a glance" A figure for the API Documentation section might be helpful for example.
- [x] there are many suggested rewordings and comments on how to improve the text here: https://docs.google.com/document/d/1tU0lrjmdRu0NrESq1K4mgcHMR7FwMt5HLQklgSw8ikQ Consider these suggestions and make improvements as possible.
- [x] consider adding a section describing the remaining functionality that needs to be added to meet all the needs of the cBioPortal project. For example, describe the need for an API query to find the PDB coordinate for a specific residue in the protein sequence ... and mention some of the challenges that need to be dealt with, such as the segmentation problem and gaps in the pdb sequence.

**Comment by juexinwang** [comment]
Thanks Robert!
