### ISSUE TITLE
choose schema and create database tables for storing sequences and alignments

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/pdb-annotation#4]
- [x] Create database tables for holding sequences. Handle sequence identifiers properly, including a mapping of original sequence identifiers from sequence database source (such as Ensembl or Uniprot)  to a set of non-redundant sequences with unique internal identifiers.
- [x] Create database tables for holding alignments between sequence database sequences and pdb sequences. Primary goal is that system can retrieve an amino acid to amino acid mapping between sequence database sequence and pdb structure coordinates (resSeq). Secondary goal is to retrieve information about entire alignment (such as alignment start / end positions and a text representation of the alignment which show matches, mismatches and gaps as shown in a blast hit report.

**Comment by pieterlukasse** [comment]
This already seems to be there. See the `MIDLINE_ALIGN, UNIPROT_ALIGN, PDB_ALIGN` fields in table `pdb_uniprot_alignment`. Maybe the only thing to do is give the `UNIPROT_ALIGN` field a more generic name?

**Comment by sheridancbio** [comment]
If the previously created tables fit well, it is not required to reinvent the schema. We probably should compare these schema to Juexin's tables in the project proposal and make sure we are covering what is needed.
