### ISSUE TITLE
plan components and packages / modules for gsoc code development

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/pdb-annotation#6]
- [ ] consider what classes and other resources are likely to be needed for the gsoc project development; draft a design list
- [ ] group new development items into components
- [ ] decide on reasonable code organization [modules, packages, paths] for components being planned

**Comment by pieterlukasse** [comment]
I would love to see some sort of diagram as well that shows the modules, their place in the cBioPortal stack and how they will interact with existing cBioPortal parts.
