### ISSUE TITLE
install and test necessary software tools for gsoc project

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/pdb-annotation#7]
- [x] Install blast and test protein alignment generation
- [x] Install database system (mysql or other rDBMS)
- [x] Install or test pdb parsing library (unless all sequence and coordinate info can be downloaded from rcsb
- [ ] Install web application container if not using spring-boot to provide a container

**Comment by pieterlukasse** [comment]
should the blast results be parsed as well?

**Comment by sheridancbio** [comment]
Yes .. we will need a way to collect blast results and parse reports. I think BioJava includes this functionality.
